services:
  - type: web
    name: mentorship-platform
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn mentorship_platform.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mentorship_platform.settings
      - key: PYTHON_VERSION
        value: 3.11
