services:
  - type: web
    name: mentorship-platform
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn mentorship_platform.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mentorship_app      # 👈 must match your actual Render DB name
          property: connectionString