# Generated by Django 5.2.4 on 2025-07-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('educationid', models.UUIDField(primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('startyear', models.IntegerField(blank=True, null=True)),
                ('endyear', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'educations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.UUIDField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('fileid', models.UUIDField(primary_key=True, serialize=False)),
                ('fileurl', models.TextField()),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('filetype', models.CharField(blank=True, max_length=50, null=True)),
                ('uploadedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Followrequests',
            fields=[
                ('followrequestid', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'followrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Learninggoals',
            fields=[
                ('learninggoalid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('targetdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learninggoals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meetingnotes',
            fields=[
                ('meetingnoteid', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('attachmentfileids', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meetingnotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('meetingid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('meetinglink', models.TextField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meetings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messageid', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('isread', models.BooleanField(blank=True, null=True)),
                ('sentat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('profileid', models.UUIDField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('linkedinurl', models.TextField(blank=True, null=True)),
                ('githuburl', models.TextField(blank=True, null=True)),
                ('twitterurl', models.TextField(blank=True, null=True)),
                ('instagramurl', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('portfoliourl', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('specializationid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specializations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('passwordhash', models.TextField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=10)),
                ('isverified', models.BooleanField(blank=True, null=True)),
                ('isactive', models.BooleanField(blank=True, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userspecializations',
            fields=[
                ('userspecializationid', models.UUIDField(primary_key=True, serialize=False)),
                ('proficiency', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=10, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userspecializations',
                'managed': False,
            },
        ),
    ]
